### PR TITLE
Push notification initial testing

### PR DESCRIPTION
**Pull request by DJRHails**

### CODE REVIEW

**Comment by felination** [comment]
why do we want to merge this into master?

**Comment by felination** [comment]
NB: Branched off before CI config was set up, so will fail CI by default - I feel this should be merged into dev-skeleton not master

**Comment by felination** [comment]
State of notifications: As currently they are only sendable to android devices and this laptop doesn't seem to want to emulate one, I am probably not best suited to continue down this path. Have already begun trying to familiarise myself much more with the more front end based flutter code so will probably pick up tomorrow with something simple like the actual onboarding page and then try to be properly useful there

**Comment by DJRHails** [comment]
Needs to be rebased off of dev-skeleton

**Comment by DJRHails** [comment]
@felination fix your style pls `flutter analyse`

**Review by felination — APPROVED** [review]

**Pull request merged**
