### PR TITLE
[PR] Name Input Page

### PR DESCRIPTION
**Pull request by DJRHails**

### CODE REVIEW

**Comment by felination** [comment]
@DJRHails There was a build error and this branch needs the new changes from master merged/squashed in before this pull request can be completed

**Comment by felination** [comment]
@DJRHails Just need to fix conflicts/out of date issues with master then I'm happy to approve a review

**Review by JamesDalboth — DISMISSED** [review]

**Comment by DJRHails** [comment]
@felination Fixed 👍

**Review by felination — APPROVED** [review]

**Comment by felination** [comment]
Have left a confirm review on this now, now one other person needs to too and then this can be merged

**Review by matt-malarkey — APPROVED** [review]

**Pull request merged**
